//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpcomingMoviesApp {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UpcomingMoviesApp.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ErrorNoConnection {
            get {
                return ResourceManager.GetString("ErrorNoConnection", resourceCulture);
            }
        }
        
        internal static string ErrorSearchingGenres {
            get {
                return ResourceManager.GetString("ErrorSearchingGenres", resourceCulture);
            }
        }
        
        internal static string ErrorSearchingMovies {
            get {
                return ResourceManager.GetString("ErrorSearchingMovies", resourceCulture);
            }
        }
        
        internal static string MoviesPageTitle {
            get {
                return ResourceManager.GetString("MoviesPageTitle", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string SearchMovies {
            get {
                return ResourceManager.GetString("SearchMovies", resourceCulture);
            }
        }
        
        internal static string TypeAtLeast5CharactersToSearch {
            get {
                return ResourceManager.GetString("TypeAtLeast5CharactersToSearch", resourceCulture);
            }
        }
        
        internal static string NoRecordsFound {
            get {
                return ResourceManager.GetString("NoRecordsFound", resourceCulture);
            }
        }
    }
}
